name: CI/CD Pipeline

on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and Push Images (amd64 only)
        run: |
          docker buildx build --platform linux/amd64 \
            -t ${{ secrets.ACR_LOGIN_SERVER }}/product_service:${{ github.sha }} \
            -t ${{ secrets.ACR_LOGIN_SERVER }}/product_service:latest \
            ./backend/product_service --push

          docker buildx build --platform linux/amd64 \
            -t ${{ secrets.ACR_LOGIN_SERVER }}/order_service:${{ github.sha }} \
            -t ${{ secrets.ACR_LOGIN_SERVER }}/order_service:latest \
            ./backend/order_service --push

          docker buildx build --platform linux/amd64 \
            -t ${{ secrets.ACR_LOGIN_SERVER }}/frontend:${{ github.sha }} \
            -t ${{ secrets.ACR_LOGIN_SERVER }}/frontend:latest \
            ./frontend --push

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3

      - name: Set up AKS context
        uses: azure/aks-set-context@v3
        with:
          resource-group: ${{ secrets.AKS_RESOURCE_GROUP }}
          cluster-name: ${{ secrets.AKS_CLUSTER_NAME }}

      - name: Create Kubernetes Secrets
        run: |
          kubectl create secret generic ecomm-secrets --from-literal=POSTGRES_USER=${{ secrets.POSTGRES_USER }} \
            --from-literal=POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} \
            --from-literal=AZURE_STORAGE_ACCOUNT_NAME=${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }} \
            --from-literal=AZURE_STORAGE_ACCOUNT_KEY=${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }} --dry-run=client -o yaml | kubectl apply -f -

      - name: Deploy to AKS
        run: kubectl apply -f k8s/
